### PR TITLE
feat: multiple ugrades to allow for more flexibility

### LINKED ISSUE #46: Feature Request: assign/label based on keyword in title OR body
It would be great to add a field to select whether you want to match keywords in the title of the issue or the body or both. 

In my case I need to only check the title.

I'll try to put in a PR for this.

### LINKED ISSUE #49: Feature request: check both issues and PRs
It would be great to be able to use this action to auto label and assign PRs as well as issues based on keywords.

 I will try to put in a PR for this.

### LINKED ISSUE #72: Feature Request: multiple keyword/label/assignee checks at once
Add ability to check for multiple keyword/label/assignee in one run by passing a json instead of having different fields.

Will submit a PR soon.

### PR DESCRIPTION
**Pull request by SomayaB**
- Adds ability to check either issues, pull requests or both for matching keywords.
- Adds ability to check the issue, the issue body or both for matching keywords.
The `title-or-body` field takes either `'title'`, `'body'`, or `'both'`.
- Instead of only being able to look for one keyword/label/assignee match per run, adds the ability to pass in a `parameters` JSON array in order to check for multiple keywords and add their corresponding labels and assignees.

```yaml
name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened]
  pull_requests:
    typed: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          title-or-body: 'both'
          parameters: '[ {"keywords": ["bug", "error"], "labels": ["BUG"], "assignees": ["username"]}, {"keywords": ["help", "guidance"], "labels": ["help-wanted"], "assignees": ["username"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
```

Closes #46 
Closes #49 
Closes #72

### CODE REVIEW

**Comment by SomayaB** [comment]
@Naturalclar There's a test failing but I really can't figure out why. It was working locally. Thoughts?

**Comment by Naturalclar** [comment]
@SomayaB thank you! I'll take a look at it over the weekend

**Comment by Naturalclar** [comment]
@SomayaB seems like the `getIssueContent` test is failing on a PR, since it's not using the same github credentials, resulting the error to be `Bad Credentials` instead of `No Issue Provided` . I need to figure out a way for this to work when a PR is made from a fork... :thinking:

**Comment by Naturalclar** [comment]
just released v2.0.0 with your change :tada:

**Pull request merged**
