### PR TITLE
No quotes around parameters value

### PR DESCRIPTION
**Pull request by DelazJ**

### CODE REVIEW

**Review by afonsojramos — CHANGES_REQUESTED** [review]
This is incorrect. `parameters` can only accept a `string | number | boolean`

**Comment by DelazJ** [comment]
What i can say is that I got [this error](https://github.com/qgis/QGIS-Documentation/runs/5246100020?check_suite_focus=true) until I removed the `'`. Things are then green as you can see in https://github.com/qgis/QGIS-Documentation/actions/workflows/auto-label.yml

**Comment by afonsojramos** [comment]
I'll test it out locally, but what VSCode shows is this: 
image

**Comment by afonsojramos** [comment]
@DelazJ Indeed that is correct!

**Review by afonsojramos — APPROVED** [review]

**Review by Naturalclar — APPROVED** [review]
thanks for the fix!

**Pull request merged**
